### ISSUE TITLE
About page - Incorrect link to Github site for the code

### ISSUE THREAD

**Issue by JoePlant** [Rmadillo/business_intelligence_with_r#1]
Hi I was looking at your book and saw that you have links to the code on Github.  This link seems to be broken and is currently pointing to https://github.com/Rmadillo/business_intelligence_with_r/code

**Comment by Rmadillo** [comment]
Thanks Joseph! I'll get that fixed.

Actual url is https://github.com/Rmadillo/business_intelligence_with_r/tree/master/manuscript/code

On Jul 13, 2016, at 4:06 PM, Joseph Plant <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi I was looking at your book and saw that you have links to the code on Github. This link seems to be broken and is currently pointing to https://github.com/Rmadillo/business_intelligence_with_r/code

##

**Comment by JoePlant** [comment]
Fixed in latest release.
