### ISSUE TITLE
Colon character in filename prevents Windows users from cloning the repo

### ISSUE THREAD

**Issue by BenRussert** [Rmadillo/business_intelligence_with_r#4]
The filename "manuscript/ images/ Screenshot from 2015-02-28 14:46:39. png" cannot be created on Windows since colon character is illegal for filenames. This prevents git clone from completing for the repo.

Enjoying the book so far, hope this info helps.

**Comment by Rmadillo** [comment]
Thanks! Leftover cruft from early dev--I probably never would have noticed if you hadn't mentioned it! Gone now.
