### ISSUE TITLE
Error in chap1 rmd # Create a DateTime object

### ISSUE THREAD

**Issue by alevy59** [Rmadillo/business_intelligence_with_r#6]
When running chunk by chunk from rmd file I've got an error:
# Create a DateTime object
```{r}
power$DateTime = as.POSIXct(paste(power$Date, power$Time))
# this will take even more time 
```
Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format

**Comment by Rmadillo** [comment]
I can't seem to recreate your error. That line runs fine for me whether knitring it all at once as well as running it by chunk and line-by-line. 

You are referring to the file `BIWR_Chapter_1_Hauteville_House_Power_Forecast_20101127.Rmd`, correct?

**Comment by Rmadillo** [comment]
No response; closing.
